require "configs.alpha"
require "configs.autopairs"
require "configs.bufferline"
require "configs.comment"
require "configs.gitsigns"
require "configs.impatient"
require "configs.lualine"
--[[ require "configs.markdown-preview" ]]
require "configs.notify"
require "configs.nvim-cmp"
require "configs.nvim-tree"
require "configs.project"
require "configs.telescope"
require "configs.toggleterm"
require "configs.treesitter"
require "configs.which-key"
