require "user.configs.alpha"
require "user.configs.autopairs"
require "user.configs.bufferline"
require "user.configs.comment"
require "user.configs.gitsigns"
require "user.configs.impatient"
require "user.configs.lualine"
--[[ require "user.configs.markdown-preview" ]]
require "user.configs.notify"
require "user.configs.nvim-cmp"
require "user.configs.nvim-tree"
require "user.configs.project"
require "user.configs.telescope"
require "user.configs.toggleterm"
require "user.configs.treesitter"
require "user.configs.which-key"
